server:
  port: 8090
eureka:
  client:
    service-url:
      defaultZone : https://eureka-service-ufps.herokuapp.com/eureka

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
      routes:
        - id: authmicroservice
          uri: https://auth-microservice-ufps.herokuapp.com/
          filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/auth/**
        - id: registermicroservice
          uri: https://room-registration-microservice.herokuapp.com/
          filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/roomregister/**
  application:
    name: api-gateway
